const pacientesData = [
  {
    id: 1,
    nombrePaciente: "hector emilio",
    apellidoPaternoPaciente: "velasquez",
    apellidoMaternoPaciente: "Pérez",
    fechaNacimientoPaciente: "Tue Mar 08 2022 07:47:48 GMT-0600",
    edadPaciente: 34,
    correoelectronicoWhatsescogerPaciente: "correoelectronicodirigido",
    correoelectronicoWhatsescribirPaciente: "hectoremilio1000@gmail.com",
    nombrePrueba: "covid antigenos",
    horaMuestraPaciente: "Wed Mar 16 2022 06:04:04 GMT-0600",
    costoPrueba: 600,
    formaPagoPacientes: "tarjeta",
    resultadoPrueba: "positivo",
    realizadopor: "dania",
    lugarTomaMuestraEscoger: "sucursal",
    direccionMuestra: "undefined",
    dirigidoa: "miguel",
    correoWhatsDirigidoEscoger: "correoelectronicodirigido",
    correoelectronicoWhatsDirigidoDefinir: "drmiguel1980@gmail.com",
    MandadoRecomendado: "miguel",
  },
  {
    id: 2,
    nombrePaciente: "juan",
    apellidoPaternoPaciente: "piedras",
    apellidoMaternoPaciente: "francisco",
    fechaNacimientoPaciente: "Tue Mar 08 2022 07:47:48 GMT-0600",
    edadPaciente: 34,
    correoelectronicoWhatsescogerPaciente: "correoelectronicodirigido",
    correoelectronicoWhatsescribirPaciente: "hectoremilio1000@gmail.com",
    nombrePrueba: "covid antigenos",
    horaMuestraPaciente: "Wed Mar 16 2022 06:04:04 GMT-0600",
    costoPrueba: 600,
    formaPagoPacientes: "tarjeta",
    resultadoPrueba: "positivo",
    realizadopor: "dania",
    lugarTomaMuestraEscoger: "sucursal",
    direccionMuestra: "undefined",
    dirigidoa: "miguel",
    correoWhatsDirigidoEscoger: "correoelectronicodirigido",
    correoelectronicoWhatsDirigidoDefinir: "drmiguel1980@gmail.com",
    MandadoRecomendado: "miguel",
  },
];
